namespace later_list
{
    public static class Genres
    {
        private static string[] movieGenres = {"Action",
                                            "Adventure",
                                            "Animation",
                                            "Biography",
                                            "Comedy",
                                            "Crime",
                                            "Documentary",
                                            "Drama",
                                            "Family",
                                            "Fantasy",
                                            "Film Noir",
                                            "History",
                                            "Horror",
                                            "Music",
                                            "Musical",
                                            "Mystery",
                                            "Romance",
                                            "Sci-Fi",
                                            "Short",
                                            "Sitcom",
                                            "Sport",
                                            "Superhero",
                                            "Thriller",
                                            "War",
                                            "Western"};
        private static string[] serieGenres = {"Action",
                                             "Adventure",
                                             "Animation",
                                             "Biography",
                                             "Comedy",
                                             "Crime",
                                             "Documentary",
                                             "Drama",
                                             "Family",
                                             "Fantasy",
                                             "Film Noir",
                                             "History",
                                             "Horror",
                                             "Music",
                                             "Musical",
                                             "Mystery",
                                             "Romance",
                                             "Sci-Fi",
                                             "Short",
                                             "Sitcom",
                                             "Sport",
                                             "Superhero",
                                             "Thriller",
                                             "War",
                                             "Western"};
        private static string[] bookGenres = {"Action and Adventure",
                                            "Anthology",
                                            "Biography/Autobiography",
                                            "Classic",
                                            "Comic and Graphic Novel",
                                            "Crime and Detective",
                                            "Drama",
                                            "Essay",
                                            "Fable",
                                            "Fairy Tale",
                                            "Fan-Fiction",
                                            "Fantasy",
                                            "Historical Fiction",
                                            "Horror",
                                            "Humor",
                                            "Legend",
                                            "Magical Realism",
                                            "Memoir",
                                            "Mystery",
                                            "Mythology",
                                            "Narrative Nonfiction",
                                            "Periodicals",
                                            "Realistic Fiction",
                                            "Reference Books",
                                            "Romance",
                                            "Satire",
                                            "Self-help Book",
                                            "Sci-Fi",
                                            "Short Story",
                                            "Speech",
                                            "Suspense/Thriller",
                                            "Textbook",
                                            "Poetry"};

        public static string[] GetGenres(MainForm.Sections section)
        {
            if (section == MainForm.Sections.Movie) return movieGenres;
            if (section == MainForm.Sections.Serie) return serieGenres;
            if (section == MainForm.Sections.Book)  return bookGenres;
            return null;
        }
    }
}
